# Generated by Django 5.0.10 on 2026-03-24 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_securitylog_entry_exit_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('management', 'Management'), ('company', 'Company')], default='management', max_length=20)),
                ('default_driver_type', models.CharField(choices=[('owner', 'Owner'), ('other', 'Other')], default='owner', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'plate'],
                'indexes': [models.Index(fields=['category', 'plate'], name='core_vehicl_categor_b19d1d_idx'), models.Index(fields=['is_active', 'category'], name='core_vehicl_is_acti_c2ab32_idx')],
            },
        ),
    ]
