from django.urls import path

from .views import (
    AbsenceRecordDetailView,
    AbsenceRecordListCreateView,
    AbsenceRecordCancelView,
    AbsenceRecordHRApproveView,
    AbsenceRecordManagerApproveView,
    AbsenceRecordRejectView,
    AbsenceTypeDetailView,
    AbsenceTypeListCreateView,
    AttendanceSummaryView,
    AuditLogListView,
    AuthLoginView,
    BadgeDetailView,
    BadgeListCreateView,
    AuthMeView,
    CheckView,
    DeviceAuthView,
    HostPresetDetailView,
    HostPresetListCreateView,
    LogListView,
    LogSyncView,
    PayrollProfileDetailView,
    PayrollProfileListCreateView,
    PersonDetailView,
    PersonListCreateView,
    PayrollSummaryView,
    SGKReportView,
    ShiftAssignmentDetailView,
    ShiftAssignmentListCreateView,
    VehiclePresetDetailView,
    VehiclePresetListCreateView,
    WorkShiftDetailView,
    WorkShiftListCreateView,
)


urlpatterns = [
    path('auth/login', AuthLoginView.as_view(), name='auth_login'),
    path('auth/me', AuthMeView.as_view(), name='auth_me'),
    path('auth/audit', AuditLogListView.as_view(), name='auth_audit'),
    path('device/auth', DeviceAuthView.as_view(), name='device_auth'),
    path('check', CheckView.as_view(), name='check'),
    path('logs', LogListView.as_view(), name='logs_list'),
    path('logs/sync', LogSyncView.as_view(), name='logs_sync'),
    path('persons', PersonListCreateView.as_view(), name='person_list'),
    path('persons/<uuid:pk>', PersonDetailView.as_view(), name='person_detail'),
    path('badges', BadgeListCreateView.as_view(), name='badge_list'),
    path('badges/<uuid:pk>', BadgeDetailView.as_view(), name='badge_detail'),
    path('host-presets', HostPresetListCreateView.as_view(), name='host_preset_list'),
    path('host-presets/<uuid:pk>', HostPresetDetailView.as_view(), name='host_preset_detail'),
    path('vehicle-presets', VehiclePresetListCreateView.as_view(), name='vehicle_preset_list'),
    path('vehicle-presets/<uuid:pk>', VehiclePresetDetailView.as_view(), name='vehicle_preset_detail'),
    path('absence/types', AbsenceTypeListCreateView.as_view(), name='absence_type_list'),
    path('absence/types/<uuid:pk>', AbsenceTypeDetailView.as_view(), name='absence_type_detail'),
    path('absence/records', AbsenceRecordListCreateView.as_view(), name='absence_record_list'),
    path('absence/records/<uuid:pk>', AbsenceRecordDetailView.as_view(), name='absence_record_detail'),
    path('absence/records/<uuid:pk>/approve/manager', AbsenceRecordManagerApproveView.as_view(), name='absence_record_approve_manager'),
    path('absence/records/<uuid:pk>/approve/hr', AbsenceRecordHRApproveView.as_view(), name='absence_record_approve_hr'),
    path('absence/records/<uuid:pk>/reject', AbsenceRecordRejectView.as_view(), name='absence_record_reject'),
    path('absence/records/<uuid:pk>/cancel', AbsenceRecordCancelView.as_view(), name='absence_record_cancel'),
    path('shifts', WorkShiftListCreateView.as_view(), name='work_shift_list'),
    path('shifts/<uuid:pk>', WorkShiftDetailView.as_view(), name='work_shift_detail'),
    path('shift-assignments', ShiftAssignmentListCreateView.as_view(), name='shift_assignment_list'),
    path('shift-assignments/<uuid:pk>', ShiftAssignmentDetailView.as_view(), name='shift_assignment_detail'),
    path('attendance/summary', AttendanceSummaryView.as_view(), name='attendance_summary'),
    path('payroll/profiles', PayrollProfileListCreateView.as_view(), name='payroll_profile_list'),
    path('payroll/profiles/<uuid:pk>', PayrollProfileDetailView.as_view(), name='payroll_profile_detail'),
    path('payroll/summary', PayrollSummaryView.as_view(), name='payroll_summary'),
    path('sgk/report', SGKReportView.as_view(), name='sgk_report'),
]
